# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create!(username: 'admin', password: 'admin')

Owner.create!(name:"Al Pesh")
Owner.create!(name:"CHESTNUT PETROLEUM")
Owner.create!(name:"COURTESY MARTS")
Owner.create!(name:"DALIP")
Owner.create!(name:"Dominic Hartford Shells")
Owner.create!(name:"FOAM & WASH")
Owner.create!(name:"foamwash")
Owner.create!(name:"Gary")
Owner.create!(name:"Gary Patel")
Owner.create!(name:"ISSA & REYAD")
jeff = Owner.create!(name:"JEFF RAFIQ & SAM")
Owner.create!(name:"KP")
Owner.create!(name:"MIKE GENSINGER")
Owner.create!(name:"MISC OWNERS")
Owner.create!(name:"MUSTAPHA JAMAL")
Owner.create!(name:"Nick")
Owner.create!(name:"NICK AND ANDY")
Owner.create!(name:"PRESTIGE PETROLEUM")
Owner.create!(name:"Sobhi&Anass Clinton ct")
Owner.create!(name:"SUNNY CHAUDHRY")
Owner.create!(name:"Sunny Patel")
Owner.create!(name:"TEDDY ZORBIS")

jeff.businesses.create!(name:"Beacon Main st deli")
jeff.businesses.create!(name:"Beacon_Coastal 145 Fishkill")
jeff.businesses.create!(name:"Beacon_Durkins Deli")
jeff.businesses.create!(name:"Beacon_Gas Line_(Citgo) 220 main st")
jeff.businesses.create!(name:"Beacon_Gulf")
jeff.businesses.create!(name:"Bobs Cornerstore")
jeff.businesses.create!(name:"Brewster")
jeff.businesses.create!(name:"Cheshire mini mart bp")
jeff.businesses.create!(name:"Citgo rhinebeck")
jeff.businesses.create!(name:"Crazy Chicken Deli_Poughkeepsie")
jeff.businesses.create!(name:"Hughsonville Deli")
jeff.businesses.create!(name:"Kingston_Citgo")
jeff.businesses.create!(name:"Lotto store")
jeff.businesses.create!(name:"Market st.-Poughkeepsie_Sunoco")
jeff.businesses.create!(name:"Middlefield groceries")
jeff.businesses.create!(name:"Milford")
jeff.businesses.create!(name:"Monticello Exxon")
jeff.businesses.create!(name:"ODells_Citgo")
jeff.businesses.create!(name:"Parker Ave._Exxon")
jeff.businesses.create!(name:"Sams Food Mart_Poughkeepsie")
jeff.businesses.create!(name:"Stanfordville_Sunoco")
jeff.businesses.create!(name:"Stormville Citgo")
jeff.businesses.create!(name:"Westbrookville Deli")